# Generated by Django 3.2.12 on 2022-07-29 12:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('memo', models.TextField(blank=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('datecompleted', models.DateTimeField(blank=True, null=True)),
                ('everyday', models.BooleanField(default=False)),
                ('level', models.SmallIntegerField(choices=[(1, '普通任务'), (2, '优先任务'), (0, '不紧急任务'), (3, '突发紧急任务')], default=0, verbose_name='任务重要性')),
                ('status', models.SmallIntegerField(choices=[(0, '未开始'), (1, '进行中'), (2, '已结束')], default=0, verbose_name='任务状态')),
                ('expiration_date', models.DateTimeField(verbose_name='任务截止日期')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
