# Generated by Django 3.2.12 on 2022-07-29 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='level',
            field=models.SmallIntegerField(choices=[(1, '普通任务'), (0, '不紧急任务'), (3, '突发紧急任务'), (2, '优先任务')], default=0, verbose_name='任务重要性'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='status',
            field=models.SmallIntegerField(choices=[(1, '进行中'), (2, '已结束'), (3, '已过期'), (0, '未开始')], default=0, verbose_name='任务状态'),
        ),
    ]
