# Generated by Django 3.2.12 on 2022-08-04 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_auto_20220804_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='level',
            field=models.SmallIntegerField(choices=[(2, '优先任务'), (3, '突发紧急任务'), (0, '不紧急任务'), (1, '普通任务')], default=0, verbose_name='任务重要性'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='status',
            field=models.SmallIntegerField(choices=[(0, '未开始'), (3, '已过期'), (1, '进行中'), (2, '已完成')], default=0, verbose_name='任务状态'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='tag',
            field=models.SmallIntegerField(choices=[(4, '休闲'), (1, '学习'), (2, '饮食'), (6, '其他'), (0, '运动'), (3, '工作'), (5, '生活')], default=0, verbose_name='标签'),
        ),
    ]
