# Generated by Django 3.2.12 on 2022-08-07 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_auto_20220807_2119'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='single_time',
            field=models.CharField(default='00:00', max_length=10, verbose_name='当日时间'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='level',
            field=models.SmallIntegerField(choices=[(1, '普通任务'), (0, '不紧急任务'), (2, '优先任务'), (3, '突发紧急任务')], default=0, verbose_name='任务重要性'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='status',
            field=models.SmallIntegerField(choices=[(0, '未开始'), (2, '已完成'), (1, '进行中'), (3, '已过期')], default=0, verbose_name='任务状态'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='tag',
            field=models.SmallIntegerField(choices=[(6, '其他'), (1, '学习'), (2, '饮食'), (4, '休闲'), (3, '工作'), (5, '生活'), (0, '运动')], default=0, verbose_name='标签'),
        ),
    ]
