# Generated by Django 3.2.12 on 2022-08-01 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_auto_20220730_2000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='expiration_date',
            field=models.DateTimeField(blank=True, default='2020-01-01', null=True, verbose_name='任务截止日期'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='level',
            field=models.SmallIntegerField(choices=[(3, '突发紧急任务'), (2, '优先任务'), (1, '普通任务'), (0, '不紧急任务')], default=0, verbose_name='任务重要性'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='status',
            field=models.SmallIntegerField(choices=[(1, '进行中'), (0, '未开始'), (3, '已过期'), (2, '已完成')], default=0, verbose_name='任务状态'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='tag',
            field=models.SmallIntegerField(choices=[(5, '生活'), (1, '学习'), (6, '其他'), (0, '运动'), (4, '休闲'), (2, '饮食'), (3, '工作')], default=0, verbose_name='标签'),
        ),
    ]
