# Generated by Django 4.0.6 on 2022-08-08 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_auto_20220807_2120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='level',
            field=models.SmallIntegerField(choices=[(3, '突发紧急任务'), (2, '优先任务'), (0, '不紧急任务'), (1, '普通任务')], default=0, verbose_name='任务重要性'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='status',
            field=models.SmallIntegerField(choices=[(2, '已完成'), (1, '进行中'), (0, '未开始'), (3, '已过期')], default=0, verbose_name='任务状态'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='tag',
            field=models.SmallIntegerField(choices=[(1, '学习'), (3, '工作'), (5, '生活'), (0, '运动'), (6, '其他'), (2, '饮食'), (4, '休闲')], default=0, verbose_name='标签'),
        ),
    ]
